language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=^3.0
    - COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=3.0.* COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION=dev-master

matrix:
    fast_finish: true

    exclude:
        - php: 5.4
          env: SYMFONY_VERSION=3.0.*
        - php: 5.4
          env: SYMFONY_VERSION=3.0.* COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.4
          env: SYMFONY_VERSION=^3.0
        - php: 5.4
          env: SYMFONY_VERSION=dev-master

    allow_failures:
        - php: 7
        - php: hhvm
        - php: nightly
        - env: SYMFONY_VERSION=dev-master

before_install:
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors --coverage-text
